export const fakeMeetings = [
  {
    id: 1,
    title: "Entrevista para vaga Desenvolvedor",
    responsavel: "Ana",
    categoria: "Recursos Humanos",
    data: "01/01/2021",
    duracao: "1h 10m",
  },
  {
    id: 2,
    title: "Reunião de Alinhamento Projeto X",
    responsavel: "Carlos",
    categoria: "Planejamento Estratégico",
    data: "02/01/2021",
    duracao: "2h 00m",
  },
  {
    id: 3,
    title: "Daily do Projeto Y",
    responsavel: "Fernanda",
    categoria: "Desenvolvimento de Produto",
    data: "03/01/2021",
    duracao: "0h 30m",
  },
  {
    id: 4,
    title: "Entrevista para vaga Analista de Dados",
    responsavel: "José",
    categoria: "Recursos Humanos",
    data: "04/01/2021",
    duracao: "1h 00m",
  },
  {
    id: 5,
    title: "Reunião de Vendas Mensal",
    responsavel: "Paulo",
    categoria: "Vendas",
    data: "05/01/2021",
    duracao: "1h 45m",
  },
  {
    id: 6,
    title: "Planejamento de Campanha de Marketing",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "06/01/2021",
    duracao: "2h 15m",
  },
  {
    id: 7,
    title: "Daily do Projeto Z",
    responsavel: "Ricardo",
    categoria: "Desenvolvimento de Produto",
    data: "07/01/2021",
    duracao: "0h 20m",
  },
  {
    id: 8,
    title: "Reunião de Feedback",
    responsavel: "Lucia",
    categoria: "Recursos Humanos",
    data: "08/01/2021",
    duracao: "1h 30m",
  },
  {
    id: 9,
    title: "Reunião de Alinhamento Estratégico",
    responsavel: "Roberto",
    categoria: "Planejamento Estratégico",
    data: "09/01/2021",
    duracao: "2h 30m",
  },
  {
    id: 10,
    title: "Entrevista para vaga Designer",
    responsavel: "Ana",
    categoria: "Recursos Humanos",
    data: "10/01/2021",
    duracao: "1h 00m",
  },
  {
    id: 11,
    title: "Reunião de Planejamento de Produto",
    responsavel: "Carlos",
    categoria: "Desenvolvimento de Produto",
    data: "11/01/2021",
    duracao: "2h 00m",
  },
  {
    id: 12,
    title: "Reunião de Marketing Digital",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "12/01/2021",
    duracao: "1h 45m",
  },
  {
    id: 13,
    title: "Reunião de Estratégia de Vendas",
    responsavel: "Paulo",
    categoria: "Vendas",
    data: "13/01/2021",
    duracao: "1h 30m",
  },
  {
    id: 14,
    title: "Daily do Projeto X",
    responsavel: "Fernanda",
    categoria: "Desenvolvimento de Produto",
    data: "14/01/2021",
    duracao: "0h 25m",
  },
  {
    id: 15,
    title: "Entrevista para vaga Gerente de Projetos",
    responsavel: "José",
    categoria: "Recursos Humanos",
    data: "15/01/2021",
    duracao: "1h 20m",
  },
  {
    id: 16,
    title: "Reunião de Planejamento Anual",
    responsavel: "Lucia",
    categoria: "Planejamento Estratégico",
    data: "16/01/2021",
    duracao: "2h 45m",
  },
  {
    id: 17,
    title: "Reunião de Branding",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "17/01/2021",
    duracao: "1h 50m",
  },
  {
    id: 18,
    title: "Reunião de Resultados do Trimestre",
    responsavel: "Ricardo",
    categoria: "Vendas",
    data: "18/01/2021",
    duracao: "1h 15m",
  },
  {
    id: 19,
    title: "Entrevista para vaga Assistente Administrativo",
    responsavel: "Ana",
    categoria: "Recursos Humanos",
    data: "19/01/2021",
    duracao: "0h 45m",
  },
  {
    id: 20,
    title: "Reunião de Melhoria Contínua",
    responsavel: "Roberto",
    categoria: "Planejamento Estratégico",
    data: "20/01/2021",
    duracao: "1h 40m",
  },
  {
    id: 21,
    title: "Daily do Projeto W",
    responsavel: "Fernanda",
    categoria: "Desenvolvimento de Produto",
    data: "21/01/2021",
    duracao: "0h 35m",
  },
  {
    id: 22,
    title: "Reunião de Revisão de Produto",
    responsavel: "Carlos",
    categoria: "Desenvolvimento de Produto",
    data: "22/01/2021",
    duracao: "1h 00m",
  },
  {
    id: 23,
    title: "Planejamento de Campanha Social",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "23/01/2021",
    duracao: "1h 30m",
  },
  {
    id: 24,
    title: "Reunião de Planejamento de Vendas",
    responsavel: "Paulo",
    categoria: "Vendas",
    data: "24/01/2021",
    duracao: "1h 10m",
  },
  {
    id: 25,
    title: "Entrevista para vaga de Estagiário",
    responsavel: "José",
    categoria: "Recursos Humanos",
    data: "25/01/2021",
    duracao: "0h 30m",
  },
  {
    id: 26,
    title: "Reunião de Avaliação de Riscos",
    responsavel: "Roberto",
    categoria: "Planejamento Estratégico",
    data: "26/01/2021",
    duracao: "2h 20m",
  },
  {
    id: 27,
    title: "Daily do Projeto V",
    responsavel: "Ricardo",
    categoria: "Desenvolvimento de Produto",
    data: "27/01/2021",
    duracao: "0h 40m",
  },
  {
    id: 28,
    title: "Reunião de Revisão de Marca",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "28/01/2021",
    duracao: "1h 25m",
  },
  {
    id: 29,
    title: "Reunião de Alinhamento de Equipe",
    responsavel: "Lucia",
    categoria: "Recursos Humanos",
    data: "29/01/2021",
    duracao: "1h 00m",
  },
  {
    id: 30,
    title: "Reunião de Estratégia de Crescimento",
    responsavel: "Roberto",
    categoria: "Planejamento Estratégico",
    data: "30/01/2021",
    duracao: "2h 15m",
  },
  {
    id: 31,
    title: "Reunião de Roadmap de Produto",
    responsavel: "Carlos",
    categoria: "Desenvolvimento de Produto",
    data: "31/01/2021",
    duracao: "1h 55m",
  },
  {
    id: 32,
    title: "Daily do Projeto U",
    responsavel: "Fernanda",
    categoria: "Desenvolvimento de Produto",
    data: "01/02/2021",
    duracao: "0h 30m",
  },
  {
    id: 33,
    title: "Entrevista para vaga de Vendas",
    responsavel: "José",
    categoria: "Recursos Humanos",
    data: "02/02/2021",
    duracao: "1h 00m",
  },
  {
    id: 34,
    title: "Reunião de Revisão de Processos",
    responsavel: "Lucia",
    categoria: "Planejamento Estratégico",
    data: "03/02/2021",
    duracao: "2h 00m",
  },
  {
    id: 35,
    title: "Reunião de Planejamento de Conteúdo",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "04/02/2021",
    duracao: "1h 45m",
  },
  {
    id: 36,
    title: "Reunião de Prospecção de Clientes",
    responsavel: "Paulo",
    categoria: "Vendas",
    data: "05/02/2021",
    duracao: "1h 20m",
  },
  {
    id: 37,
    title: "Reunião de Ideias Inovadoras",
    responsavel: "Ricardo",
    categoria: "Desenvolvimento de Produto",
    data: "06/02/2021",
    duracao: "1h 50m",
  },
  {
    id: 38,
    title: "Daily do Projeto T",
    responsavel: "Fernanda",
    categoria: "Desenvolvimento de Produto",
    data: "07/02/2021",
    duracao: "0h 25m",
  },
  {
    id: 39,
    title: "Reunião de Revisão de Metas",
    responsavel: "Roberto",
    categoria: "Planejamento Estratégico",
    data: "08/02/2021",
    duracao: "2h 00m",
  },
  {
    id: 40,
    title: "Entrevista para vaga de Atendimento",
    responsavel: "Ana",
    categoria: "Recursos Humanos",
    data: "09/02/2021",
    duracao: "0h 50m",
  },
  {
    id: 41,
    title: "Reunião de Estratégia de Mídia",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "10/02/2021",
    duracao: "1h 15m",
  },
  {
    id: 42,
    title: "Reunião de Alinhamento Semanal",
    responsavel: "Lucia",
    categoria: "Recursos Humanos",
    data: "11/02/2021",
    duracao: "1h 30m",
  },
  {
    id: 43,
    title: "Reunião de Revisão Trimestral",
    responsavel: "Roberto",
    categoria: "Planejamento Estratégico",
    data: "12/02/2021",
    duracao: "2h 30m",
  },
  {
    id: 44,
    title: "Reunião de Estratégia de Produto",
    responsavel: "Carlos",
    categoria: "Desenvolvimento de Produto",
    data: "13/02/2021",
    duracao: "1h 40m",
  },
  {
    id: 45,
    title: "Entrevista para vaga de Desenvolvedor",
    responsavel: "José",
    categoria: "Recursos Humanos",
    data: "14/02/2021",
    duracao: "1h 10m",
  },
  {
    id: 46,
    title: "Reunião de Planejamento de Vendas",
    responsavel: "Paulo",
    categoria: "Vendas",
    data: "15/02/2021",
    duracao: "1h 35m",
  },
  {
    id: 47,
    title: "Daily do Projeto S",
    responsavel: "Fernanda",
    categoria: "Desenvolvimento de Produto",
    data: "16/02/2021",
    duracao: "0h 45m",
  },
];
