export const fakeMeetings = [
  {
    id: 1,
    title: "Reunião de Planejamento",
    responsavel: "Fulano",
    categoria: "Planejamento Estratégico",
    data: "01/01/2021",
    duracao: "1h 15m",
  },
  {
    id: 2,
    title: "Reunião de Marketing",
    responsavel: "Ciclano",
    categoria: "Marketing",
    data: "02/01/2021",
    duracao: "2h 30m",
  },
  {
    id: 3,
    title: "Reunião de Vendas",
    responsavel: "Beltrano",
    categoria: "Vendas",
    data: "03/01/2021",
    duracao: "1h 45m",
  },
  {
    id: 4,
    title: "Reunião de Desenvolvimento",
    responsavel: "Maria",
    categoria: "Desenvolvimento de Produto",
    data: "04/01/2021",
    duracao: "2h 10m",
  },
  {
    id: 5,
    title: "Reunião de Recursos Humanos",
    responsavel: "José",
    categoria: "Recursos Humanos",
    data: "05/01/2021",
    duracao: "1h 20m",
  },
  {
    id: 6,
    title: "Reunião de Planejamento de Projeto",
    responsavel: "Ana",
    categoria: "Planejamento Estratégico",
    data: "06/01/2021",
    duracao: "1h 40m",
  },
  {
    id: 7,
    title: "Reunião de Campanha Publicitária",
    responsavel: "Carlos",
    categoria: "Marketing",
    data: "07/01/2021",
    duracao: "2h 15m",
  },
  {
    id: 8,
    title: "Reunião de Treinamento de Vendas",
    responsavel: "Fernanda",
    categoria: "Vendas",
    data: "08/01/2021",
    duracao: "1h 10m",
  },
  {
    id: 9,
    title: "Reunião de Design de Produto",
    responsavel: "Paulo",
    categoria: "Desenvolvimento de Produto",
    data: "09/01/2021",
    duracao: "1h 50m",
  },
  {
    id: 10,
    title: "Reunião de Recrutamento",
    responsavel: "Lucia",
    categoria: "Recursos Humanos",
    data: "10/01/2021",
    duracao: "2h 5m",
  },
  {
    id: 11,
    title: "Reunião de Análise de Desempenho",
    responsavel: "Ricardo",
    categoria: "Planejamento Estratégico",
    data: "11/01/2021",
    duracao: "1h 30m",
  },
  {
    id: 12,
    title: "Reunião de Estratégia Digital",
    responsavel: "Juliana",
    categoria: "Marketing",
    data: "12/01/2021",
    duracao: "1h 25m",
  },
  {
    id: 13,
    title: "Reunião de Relatório de Vendas",
    responsavel: "Marcos",
    categoria: "Vendas",
    data: "13/01/2021",
    duracao: "2h 20m",
  },
  {
    id: 14,
    title: "Reunião de Lançamento de Produto",
    responsavel: "Patrícia",
    categoria: "Desenvolvimento de Produto",
    data: "14/01/2021",
    duracao: "1h 5m",
  },
  {
    id: 15,
    title: "Reunião de Avaliação de Clima Organizacional",
    responsavel: "Roberto",
    categoria: "Recursos Humanos",
    data: "15/01/2021",
    duracao: "1h 35m",
  },
  {
    id: 16,
    title: "Reunião de Revisão de Metas",
    responsavel: "Cláudia",
    categoria: "Planejamento Estratégico",
    data: "16/01/2021",
    duracao: "2h 25m",
  },
  {
    id: 17,
    title: "Reunião de Análise de Mercado",
    responsavel: "Thiago",
    categoria: "Marketing",
    data: "17/01/2021",
    duracao: "1h 55m",
  },
  {
    id: 18,
    title: "Reunião de Estratégias de Venda",
    responsavel: "Vanessa",
    categoria: "Vendas",
    data: "18/01/2021",
    duracao: "1h 45m",
  },
  {
    id: 19,
    title: "Reunião de Melhoria de Produto",
    responsavel: "Fabio",
    categoria: "Desenvolvimento de Produto",
    data: "19/01/2021",
    duracao: "2h 40m",
  },
  {
    id: 20,
    title: "Reunião de Treinamento de Equipe",
    responsavel: "Isabela",
    categoria: "Recursos Humanos",
    data: "20/01/2021",
    duracao: "1h 15m",
  },
];
